version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: 'no'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=teebay
      - POSTGRES_PASSWORD=teebay.io
      - POSTGRES_DB=teebay_db
    volumes:
      - postgresdb:/var/lib/postgresql/data/
    networks:
      - teebay-backend

  teebay-backend:
    build:
      dockerfile: Dockerfile.dev
      context: './teebay-backend'
    volumes:
      - /app/node_modules
      - ./teebay-backend:/app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - PGUSER=teebay
      - PGPASSWORD=teebay.io
      - PGDATABASE=teebay_db
      - PGHOST=postgres
    depends_on:
      - postgres
    networks:
      - teebay-backend

  teebay-frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: './teebay_fe'
    ports:
      - '4000:4000'
    volumes:
      - /app/node_modules
      - ./teebay_fe:/app
    environment:
      - PORT=4000
    networks:
      - teebay-frontend
      - teebay-backend

networks:
  teebay-frontend:
  teebay-backend:
volumes:
  postgresdb:
