export { default as Login } from "./Login"
export { default as Registration } from "./Registration"
export { default as AccountSetting } from "./AccountSetting"
export { default as AddProduct } from "./AddProduct"
export { default as Products } from "./Products"
export { default as AllProducts } from "./AllProducts"
export { default as NotFound } from "./NotFound"
